[package]
name = "malloc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphannis-malloc_size_of = "2.0.0"
graphannis-malloc_size_of_derive = "2.0.0"
