[package]
name = "my-lib"
version = "0.1.0"
edition = "2021"

include       = [
  "Cargo.toml",
  "src/**/*.rs",
  "examples/**/*.rs",
]

[dependencies]

[[example]]
name = "ex1"

# [[example]]
# name = "ex2"
