[package]
name = "use-alloc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.14.1"
bumpalo = { version = "3.13.0", features = ["allocator-api2"] }
